### ISSUE TITLE
Recuperação de Senha

### ISSUE THREAD

**Issue by hugo-loiola** [hugo-loiola/Trabalho-Mobile#10]

**Comment by digsales** [comment]
verificação de email, pode ficar chu chu beleza

**Comment by Rikelmelopes** [comment]
quando verem que a recuperação de senha vai ser feita com um código enviado no E-mail , eles não estão prontos pra isso

**Comment by MarkMaciel** [comment]
Deixa o app muito seguro com essa verificação de e-mails :)

**Comment by digsales** [comment]
![image](https://user-images.githubusercontent.com/100299845/162630570-24fe2bc1-74fb-4351-945e-e3b3930c9015.png)

A página acima verifica o email para a futura troca de senha.

![image](https://user-images.githubusercontent.com/100299845/162630598-af35f871-e028-4e80-a25b-9bc2e2599137.png)

Aqui se efetua a troca da senha, direcionando de volta a tela de login.

Esta foi a tela criado com o apoio de todos os integrantes, enquanto estávamos utilizando a plataforma online de conversa por texto, voz e vídeo, "DISCORD".

**Comment by Susanowoo** [comment]
bem loco  achei otimo o feto de termos esse tipo de preocupacao com o proximo
