### ISSUE TITLE
Página Inicial 

### ISSUE THREAD

**Issue by hugo-loiola** [hugo-loiola/Trabalho-Mobile#11]

**Comment by digsales** [comment]
essa tela assim como combinamos, deve-se estar presente: sobre as barbearias, seus serviços e também o seu endereço.

**Comment by MarkMaciel** [comment]
Tela perfeitamente ornamentada e baseada no minimalismo com a escolha perfeita de cores.

**Comment by Rikelmelopes** [comment]
essa tela vai chamar bastante atenção dos nossos clientes

**Comment by digsales** [comment]
![image](https://user-images.githubusercontent.com/100299845/162630480-f4383ad6-b46c-48c4-bf84-c66a76a70a09.png)


Esta foi a tela criado com o apoio de todos os integrantes, enquanto estávamos utilizando a plataforma online de conversa por texto, voz e vídeo, "DISCORD".

Tela com a listagem das barbearias que estão cadastradas, mostrando informações necessárias como endereço, serviço e telefone. Direciona a PESQUISA das barbearias e os PREÇOS de cada barbearia.

**Comment by Susanowoo** [comment]
a pagina inicial fico com otima simples e bem facil de ser usada  com a barra de busca ainda fico perfeita .
