### ISSUE TITLE
Preço

### ISSUE THREAD

**Issue by digsales** [hugo-loiola/Trabalho-Mobile#12]
![image](https://user-images.githubusercontent.com/100299845/162631291-2d63c796-90d6-44eb-bdf7-af106aa8341f.png)

Aqui é onde estará o preço de cada serviço das barbearias.

Esta foi a tela criado com o apoio de todos os integrantes, enquanto estávamos utilizando a plataforma online de conversa por texto, voz e vídeo, "DISCORD".

**Comment by MarkMaciel** [comment]
Os preços estão fora normal, mas é um ótimo exemplo que como ficará ao final do trabalho.

**Comment by Rikelmelopes** [comment]
a tela de preço foi baseada nas tabelas que se encontram em barbearias físicas

**Comment by Susanowoo** [comment]
preços ok
