### ISSUE TITLE
Buscas

### ISSUE THREAD

**Issue by digsales** [hugo-loiola/Trabalho-Mobile#13]
![image](https://user-images.githubusercontent.com/100299845/162631339-c486bf42-6cbe-4877-9dc2-46c786e9069d.png)

Página de busca das barbearias.
Esta foi a tela criado com o apoio de todos os integrantes, enquanto estávamos utilizando a plataforma online de conversa por texto, voz e vídeo, "DISCORD".

**Comment by Rikelmelopes** [comment]
essa ferramenta ficou bem útil para que os cliente achem as barbearias de sua regiaão ou em outros lugares

**Comment by MarkMaciel** [comment]
Ferramenta usada para facilitar a busca por barbearias dentro aplicativo.

**Comment by Susanowoo** [comment]
uma otima ferramenta ja que vamos precisa que as pessoas tenham acesso amplas  barbearias
