### ISSUE TITLE
Imagens

### ISSUE THREAD

**Issue by digsales** [hugo-loiola/Trabalho-Mobile#14]
![image](https://user-images.githubusercontent.com/100299845/162631827-68501682-41cf-4aae-8da0-55628d6d6cb2.png)

Imagens utilizadas durante a organização das telas, a nossa logo, do app "CORTE NO APP", e a imagem sugestiva da nova senha.

**Comment by MarkMaciel** [comment]
Imagens criadas para a melhor organização do trabalho.

**Comment by Susanowoo** [comment]
as imagens criadas ficaram incriveis
