### ISSUE TITLE
Quadros

### ISSUE THREAD

**Issue by digsales** [hugo-loiola/Trabalho-Mobile#15]
![image](https://user-images.githubusercontent.com/100299845/162631967-db96140b-00c0-4b68-a904-92547e6b70f0.png)

Quadros usados em nossa trabalho, o header do app e os cards das barbearias.

**Comment by MarkMaciel** [comment]
Quadros utilizados para as coisa mais básicas do trabalho, como textos e botões.

**Comment by MarkMaciel** [comment]
Quadros utilizados para as coisas mais básicas do trabalho, como textos e botões.

**Comment by Rikelmelopes** [comment]
segunda parte mais simples do trabalho, mas que faz muita diferença
