### ISSUE TITLE
Paleta de cores

### ISSUE THREAD

**Issue by digsales** [hugo-loiola/Trabalho-Mobile#2]
Aqui discutiremos a paleta conforme combinamos anteriormente.

**Comment by hugo-loiola** [comment]
Vamo usar laranja e preto no app

**Comment by hugo-loiola** [comment]
> Vamo usar laranja e preto no app



> _No description provided._
![image](https://user-images.githubusercontent.com/87447126/159812343-4070a471-33d6-4cd3-9e43-f7a981c23f19.png)

**Comment by digsales** [comment]
Essas cores aí ficaram bala no alvo, macacos me mordam... gostei!

**Comment by Susanowoo** [comment]
poxa uma clima meio superhetero mais fico muito da hora um preto tambem otimo nao pode falta...

**Comment by Susanowoo** [comment]
fico da hora curti

**Comment by MarkMaciel** [comment]
Paleta de cores perfeitamente balanceada e alinhada, muito bem escolhida pelos integrantes desse zoológico.

**Comment by Rikelmelopes** [comment]
a paleta de cores ficou exatamente do jeito que planejamos, agora vamos pra cima terminar esse projeto para que possamos nos formar e logo em seguida começarmos nossos próprios projetos

**Comment by digsales** [comment]
Mudamos parcialmente a paleta de cores, atualizamos e nos concretizamos com a seguinte paleta:

![image](https://user-images.githubusercontent.com/100299845/162632530-331d6387-a8f2-43b7-91b1-f51dc475321a.png)

**Comment by Susanowoo** [comment]
essa ainda parece fico mais de boa
