### ISSUE TITLE
Tipos

### ISSUE THREAD

**Issue by hugo-loiola** [hugo-loiola/Trabalho-Mobile#3]
Escolher quais fontes utilizar no projeto

**Comment by Rikelmelopes** [comment]
tentamos deixar as fontes realmente parecidas com o tema "Barbearia"

**Comment by MarkMaciel** [comment]
O tema barbearia é complicado de achar fontes com as características desejadas, mas fizemos o trabalho com maestria.

**Comment by digsales** [comment]
![image](https://user-images.githubusercontent.com/100299845/162631871-67fb2bd5-101c-4364-ab7b-3029c5b58821.png)

Tipografia usada ao longo da nossa jornada pelo interessante figma.

**Comment by Susanowoo** [comment]
fico bom gostei
