### ISSUE TITLE
Botões

### ISSUE THREAD

**Issue by hugo-loiola** [hugo-loiola/Trabalho-Mobile#4]

**Comment by digsales** [comment]
assim como os icones nos podemos fazer de acordo com a necessidade.

**Comment by Rikelmelopes** [comment]
os botões ficaram exatamente do jeito que planejamos no Discord

**Comment by MarkMaciel** [comment]
De acordo com as características escolhidas, fizemos os botões de forma criativa e organizada.

**Comment by digsales** [comment]
![image](https://user-images.githubusercontent.com/100299845/162632086-b917f5fb-0404-46f0-9790-06de97278436.png)

Os botões ficaram simples e bem intuitivos, criamos juntos e utilizamos durante a criação das telas.

**Comment by Susanowoo** [comment]
botoes otimos e compativeis com a palheta de cores
