### ISSUE TITLE
Input

### ISSUE THREAD

**Issue by hugo-loiola** [hugo-loiola/Trabalho-Mobile#5]

**Comment by Rikelmelopes** [comment]
na hora de codar vai ficar mais detalhadoo ainda

**Comment by MarkMaciel** [comment]
Temática minimalista com cores contrastantes com as escolhidas no componentes das telas, deixando o trabalho mais bonito visualmente.

**Comment by digsales** [comment]
![image](https://user-images.githubusercontent.com/100299845/162631579-1e2ed8d7-20e5-4146-9783-f12d91c0f8e6.png)

Inputs usados durante a confecção do app, usados no LOGIN, CADASTRO, PESQUISA etc.
