### ISSUE TITLE
Ícones

### ISSUE THREAD

**Issue by hugo-loiola** [hugo-loiola/Trabalho-Mobile#6]

**Comment by digsales** [comment]
os icones vamos ajustando de acordo com a necessidade durante a formação das páginas

**Comment by MarkMaciel** [comment]
Os ícones foram escolhidos de acordo com o tema e a necessidade do trabalho, para a criação das telas.

**Comment by Rikelmelopes** [comment]
concordo @MarkMaciel ,os ícones foram de acordo com as necessidades

**Comment by digsales** [comment]
![image](https://user-images.githubusercontent.com/100299845/162631521-6dc14bbb-764e-4933-9c63-71586a6921fe.png)

Estes foram os ícones usados na confecção das telas

**Comment by Susanowoo** [comment]
escolhido de acordo com as nescessidade e tambem de exemplos que temos dos apps atuais
