### ISSUE TITLE
Tela de Carregamento

### ISSUE THREAD

**Issue by hugo-loiola** [hugo-loiola/Trabalho-Mobile#7]

**Comment by MarkMaciel** [comment]
Simples, mas temático e eficaz, amei!

**Comment by Rikelmelopes** [comment]
esse "corte no app" bem pequeno na parte inferior da tela deu um Up no carregamento

**Comment by digsales** [comment]
![image](https://user-images.githubusercontent.com/100299845/162630000-fa4a102a-8c37-4364-9de3-31ed81f482c1.png)

Esta foi a tela criado com o apoio de todos os integrantes, enquanto estávamos utilizando a plataforma online de conversa por texto, voz e vídeo, "DISCORD".
