### ISSUE TITLE
Tela de Login

### ISSUE THREAD

**Issue by hugo-loiola** [hugo-loiola/Trabalho-Mobile#8]

**Comment by digsales** [comment]
email e senha pra entrar no app, o q acham?

**Comment by MarkMaciel** [comment]
nem precisa de email e senha pra entrar no app, acho arcaico @digsales

**Comment by Rikelmelopes** [comment]
dessa forma da mais segurança para nossos clientes

**Comment by MarkMaciel** [comment]
@digsales Acho extremante necessário, válido e simplesmente inédito, coisa que quase nunca foi visto.

**Comment by digsales** [comment]
![image](https://user-images.githubusercontent.com/100299845/162630185-a7acfa40-383d-4781-ba5e-ff3e210073e5.png)

Esta foi a tela criado com o apoio de todos os integrantes, enquanto estávamos utilizando a plataforma online de conversa por texto, voz e vídeo, "DISCORD".
Tela com a logo do nosso app, já com email e senha exigidos, direcionando para as telas seguintes, de CADASTRO, PÁGINA INICIAL ou ESQUECI A SENHA.

**Comment by Susanowoo** [comment]
melhor parte do trabalho na minha opniao
