### ISSUE TITLE
Tela de Cadastro 

### ISSUE THREAD

**Issue by hugo-loiola** [hugo-loiola/Trabalho-Mobile#9]

**Comment by digsales** [comment]
vamos fazer inspirado nas telas de login, mas com email, telefone e nome por exemplo.

**Comment by MarkMaciel** [comment]
Acrescentando as opções de cadastro como, nome, telefone e e-mail, deixamos o app pronto para a inserção de novos cadastros.

**Comment by Rikelmelopes** [comment]
essa foi parte mais divertida na minha opinião ,o que acha
 @MarkMaciel

**Comment by Rikelmelopes** [comment]
essa foi a parte mais divertida na minha opinião ,o que acha
@MarkMaciel

**Comment by MarkMaciel** [comment]
@Rikelmelopes Concordo plenamente com vc meu cumpadi, bela observação, foi deveras alegre.

**Comment by digsales** [comment]
![image](https://user-images.githubusercontent.com/100299845/162630725-33ef0609-f578-44ca-afd9-9ef739584dc8.png)

Tela de cadastro, com exigência de email, nome completo, telefone e senha.
Após o cadastro, retorna-se a tela de LOGIN.
Esta foi a tela criado com o apoio de todos os integrantes, enquanto estávamos utilizando a plataforma online de conversa por texto, voz e vídeo, "DISCORD".

**Comment by Susanowoo** [comment]
tela linda moco perfeita amei
